#ifndef _DEFINES_H
#define _DEFINES_H

#define NBFI_REV							5
#define NBFI_SUBREV							0

//#define NBFI_NO_CRYPTO

#define NBFI_DEFAULT_MANUFACTURER_ID		        0x8888     //Waviot
#define NBFI_DEFAULT_HARDWARE_TYPE_ID		        0 //UNDEFINED
#define NBFI_DEFAULT_PROTOCOL_ID		        0 //UNDEFINED

#define NBFI_DEFAULT_RF_MAX_POWER			15
#define NBFI_DEFAULT_RF_MIN_POWER			0

#define NBFI_DEFAULT_BAND_ID				UL868800_DL864000
#define NBFI_DEFAULT_SEND_INFO_INTERVAL		2592000  //one time per month
//#define MAKE_OSCCAL_INTERVAL       30

#endif // _DEFINES_H
